import type {
  ConcernDomain,
  DashboardBlueprint,
  WorkflowBlueprint,
} from "@/types/intelligence";

function steps(
  items: {
    label: string;
    role: WorkflowBlueprint["processSteps"][0]["role"];
    owner?: string;
    description?: string;
  }[]
): WorkflowBlueprint["processSteps"] {
  /** Spatial business map — zigzag flow, not a programming graph */
  return items.map((item, i) => ({
    id: `n${i + 1}`,
    label: item.label,
    role: item.role,
    owner: item.owner,
    description: item.description,
    x: i % 2 === 0 ? 72 : 340,
    y: 48 + i * 118,
  }));
}

function edges(count: number): WorkflowBlueprint["connections"] {
  return Array.from({ length: count - 1 }, (_, i) => ({
    id: `e${i + 1}`,
    from: `n${i + 1}`,
    to: `n${i + 2}`,
  }));
}

const workflowCatalog: Record<ConcernDomain, WorkflowBlueprint> = {
  delay: {
    id: "wf-delay",
    name: "بازیابی برنامه پروژه",
    objective: "بازگرداندن شناوری مسیر بحرانی و حفظ نقطه عطف قراردادی",
    whyMatters:
      "تأخیرهای تکراری بدون چرخه بازیابی استاندارد، جریمه و افت حاشیه را قطعی می‌کند.",
    businessValue: "واکنش هماهنگ زمان‌بندی، تدارکات و پیمانکار در کمتر از ۲۴ ساعت",
    kpiImprovements: [
      "کاهش ۲ روز در چرخه واکنش به شکستن مسیر بحرانی",
      "افزایش احتمال حفظ نقطه عطف تا حدود ۶۵٪",
    ],
    actors: ["مدیر پروژه", "برنامه‌ریز", "تدارکات", "پیمانکار کلیدی"],
    automationOpportunities: [
      "هشدار خودکار شکستن شناوری",
      "چک‌لیست بازیابی روزانه",
      "یادآور جلسه کارفرما",
    ],
    expectedRoi: "اجتناب از جریمه چندمیلیاردی در افق یک ماه",
    processSteps: steps([
      { label: "تشخیص شکستن مسیر", role: "start", owner: "PMO" },
      { label: "ریشه‌یابی زمان/تدارکات/پیمانکار", role: "action", owner: "مدیر پروژه" },
      { label: "آیا بازیابی داخلی کافی است؟", role: "decision", owner: "مدیر پروژه" },
      { label: "جلسه بازیابی و تخصیص منابع", role: "action", owner: "عملیات" },
      { label: "اطلاع کارفرما در صورت نیاز", role: "notify", owner: "قراردادها" },
      { label: "پایش روزانه تا بازیابی شناوری", role: "end", owner: "PMO" },
    ]),
    connections: edges(6),
  },
  cashflow: {
    id: "wf-cash",
    name: "کنترل جریان نقد اجرایی",
    objective: "هم‌ترازی وصول و پرداخت بر اساس اولویت کسب‌وکار",
    whyMatters: "فشار نقد بدون فرآیند اولویت‌بندی، پروژه‌های سالم را هم متوقف می‌کند.",
    businessValue: "تصمیم پرداخت مبتنی بر اثر عملیاتی نه صف زمانی صرف",
    kpiImprovements: ["بهبود شفافیت موقعیت نقد هفتگی", "کاهش پرداخت‌های کم‌اولویت"],
    actors: ["مدیر مالی", "مدیرعامل", "مدیر پروژه"],
    automationOpportunities: ["پیش‌نویس اولویت پرداخت هفتگی", "هشدار فشار نقد ۱۴روزه"],
    expectedRoi: "کاهش ریسک توقف ناشی از نقد در پروژه‌های کلیدی",
    processSteps: steps([
      { label: "خواندن موقعیت نقد", role: "start", owner: "مالی" },
      { label: "رتبه‌بندی تعهدات", role: "action", owner: "مالی" },
      { label: "تأیید اولویت اجرایی", role: "decision", owner: "مدیرعامل" },
      { label: "اجرای پرداخت/وصول", role: "action", owner: "مالی" },
      { label: "بازخورد به پورتفویو", role: "end", owner: "PMO" },
    ]),
    connections: edges(5),
  },
  collection: {
    id: "wf-ar",
    name: "وصول مطالبات",
    objective: "آزادی سرمایه قفل‌شده در صورت‌وضعیت‌های معوق",
    whyMatters: "وصول تکراری بدون پیگیری منظم، متوسط دوره وصول را بالا نگه می‌دارد.",
    businessValue: "پیگیری منظم کارفرما با اهرم پیشرفت و اسناد کامل",
    kpiImprovements: ["کاهش تا ۴ روز در متوسط وصول", "آزادی ۱۲ میلیارد در افق کوتاه"],
    actors: ["مالی", "مدیر پروژه", "کارفرما"],
    automationOpportunities: [
      "یادآور صورت‌وضعیت بالای ۱۰ روز",
      "چک کامل بودن اسناد قبل از ارسال",
    ],
    expectedRoi: "آزادی سرمایه در گردش معادل چند هفته عملیات",
    processSteps: steps([
      { label: "شناسایی معوق‌ها", role: "start", owner: "مالی" },
      { label: "تکمیل اسناد و پیشرفت", role: "action", owner: "پروژه" },
      { label: "اولویت‌بندی کارفرما", role: "decision", owner: "مالی" },
      { label: "پیگیری و مذاکره", role: "action", owner: "مالی" },
      { label: "ثبت وصول و آزادسازی", role: "end", owner: "مالی" },
    ]),
    connections: edges(5),
  },
  contractor: {
    id: "wf-sub",
    name: "ارزیابی پیمانکار فرعی",
    objective: "شناسایی و مهار پیمانکار پرریسک قبل از خواب جبهه",
    whyMatters: "بررسی‌های تکراری عملکرد بدون چرخه ارزیابی، ریسک را دیر نشان می‌دهد.",
    businessValue: "رتبه‌بندی ماهانه و پرداخت مشروط مبتنی بر عملکرد",
    kpiImprovements: ["شناسایی زودتر پیمانکار پرریسک تا ۱۰ روز", "کاهش خواب جبهه"],
    actors: ["عملیات", "PMO", "مالی"],
    automationOpportunities: ["امتیازدهی خودکار ماهانه", "هشدار زیرآستانه ظرفیت"],
    expectedRoi: "کاهش هزینه تأخیر ناشی از پیمانکار ضعیف",
    processSteps: steps([
      { label: "جمع‌آوری شاخص عملکرد", role: "start", owner: "PMO" },
      { label: "امتیازدهی ظرفیت/کیفیت/HSE", role: "action", owner: "عملیات" },
      { label: "زیر آستانه؟", role: "decision", owner: "عملیات" },
      { label: "پرداخت مشروط / جایگزین", role: "action", owner: "مالی" },
      { label: "ثبت نتیجه ارزیابی", role: "end", owner: "PMO" },
    ]),
    connections: edges(5),
  },
  procurement: {
    id: "wf-proc",
    name: "کنترل تدارکات بحرانی",
    objective: "حذف توقف تولید ناشی از اقلام مسیر بحرانی",
    whyMatters: "بحث‌های تکراری تدارکات بدون کنترل اقلام بلندمدت، تأخیر را نهادینه می‌کند.",
    businessValue: "دید زودهنگام کمبود و هماهنگی با برنامه",
    kpiImprovements: ["کاهش رویداد کمبود روی مسیر بحرانی", "بهبود آمادگی جبهه"],
    actors: ["تدارکات", "برنامه‌ریز", "انبار"],
    automationOpportunities: ["هشدار اقلام بلندمدت", "هم‌ترازی سفارش با شناوری"],
    expectedRoi: "جلوگیری از توقف‌های چندروزه جبهه",
    processSteps: steps([
      { label: "استخراج اقلام بحرانی", role: "start", owner: "برنامه" },
      { label: "وضعیت سفارش و انبار", role: "action", owner: "تدارکات" },
      { label: "تهدید مسیر؟", role: "decision", owner: "تدارکات" },
      { label: "تسریع / جایگزین تأمین", role: "action", owner: "تدارکات" },
      { label: "به‌روزرسانی برنامه", role: "end", owner: "PMO" },
    ]),
    connections: edges(5),
  },
  equipment: {
    id: "wf-equip",
    name: "نگهداری و بهره‌برداری تجهیزات",
    objective: "کاهش خواب و هزینه اجاره غیرضروری",
    whyMatters: "خرابی و خواب تکراری بدون چرخه نگهداری، هزینه پنهان می‌سازد.",
    businessValue: "بازتخصیص هوشمند و نگهداری پیشگیرانه",
    kpiImprovements: ["افزایش بهره‌برداری ناوگان", "کاهش اجاره اضطراری"],
    actors: ["عملیات", "نگهداری", "پروژه‌ها"],
    automationOpportunities: ["هشدار خواب بالای آستانه", "پیشنهاد بازتخصیص بین پروژه‌ها"],
    expectedRoi: "صرفه‌جویی اجاره و جلوگیری از توقف بتن‌ریزی",
    processSteps: steps([
      { label: "پایش بهره‌برداری", role: "start", owner: "عملیات" },
      { label: "تشخیص خواب / خرابی", role: "action", owner: "نگهداری" },
      { label: "تعمیر یا بازتخصیص؟", role: "decision", owner: "عملیات" },
      { label: "اجرای اقدام", role: "action", owner: "عملیات" },
      { label: "ثبت اثر هزینه", role: "end", owner: "مالی" },
    ]),
    connections: edges(5),
  },
  budget: {
    id: "wf-budget",
    name: "کنترل بودجه پروژه",
    objective: "مهار overrun قبل از تثبیت در EAC",
    whyMatters: "انحراف هزینه تکراری بدون کنترل، حاشیه را خاموش می‌خورد.",
    businessValue: "هشدار زودهنگام و تصویب هزینه خارج از برنامه",
    kpiImprovements: ["کاهش overrun شناسایی‌نشده", "شفافیت EAC"],
    actors: ["کنترل پروژه", "مالی", "مدیر پروژه"],
    automationOpportunities: ["هشدار انحراف بودجه", "صف تأیید هزینه"],
    expectedRoi: "حفظ نقاط حاشیه برنامه‌ریزی‌شده",
    processSteps: steps([
      { label: "مقایسه هزینه با بودجه", role: "start", owner: "کنترل پروژه" },
      { label: "تحلیل انحراف", role: "action", owner: "مالی" },
      { label: "نیاز به تصویب؟", role: "decision", owner: "مدیر پروژه" },
      { label: "اقدام اصلاحی", role: "action", owner: "مدیر پروژه" },
      { label: "به‌روزرسانی EAC", role: "end", owner: "مالی" },
    ]),
    connections: edges(5),
  },
  margin: {
    id: "wf-margin",
    name: "حفاظت از حاشیه سود",
    objective: "شناسایی و بستن نشتی‌های حاشیه در پورتفویو",
    whyMatters: "بحث مکرر حاشیه بدون اقدام ساختاری، سود فصل را از دست می‌دهد.",
    businessValue: "پیوند تأخیر، دستور تغییر و وصول به حاشیه",
    kpiImprovements: ["شفافیت نشتی حاشیه", "اولویت اقدام سودمحور"],
    actors: ["مدیرعامل", "مالی", "PMO"],
    automationOpportunities: ["هشدار افت حاشیه پروژه", "خلاصه هفتگی نشتی سود"],
    expectedRoi: "حفاظت از چند درصد حاشیه فصل",
    processSteps: steps([
      { label: "پایش حاشیه پروژه‌ها", role: "start", owner: "مالی" },
      { label: "تشخیص نشتی", role: "action", owner: "PMO" },
      { label: "اولویت اقدام", role: "decision", owner: "مدیرعامل" },
      { label: "اجرای اقدام", role: "action", owner: "پروژه" },
      { label: "بازبینی حاشیه", role: "end", owner: "مالی" },
    ]),
    connections: edges(5),
  },
  workforce: {
    id: "wf-crew",
    name: "تخصیص نیروی اجرایی",
    objective: "رفع کمبود نیرو روی جبهه‌های بحرانی",
    whyMatters: "کمبود تکراری نیرو بدون بازتخصیص، بهره‌وری را می‌کشد.",
    businessValue: "تخصیص بر اساس مسیر بحرانی نه عادت سایت",
    kpiImprovements: ["کاهش روزهای کمبود نیرو", "بهبود بهره‌وری جبهه"],
    actors: ["عملیات", "منابع انسانی پروژه", "PMO"],
    automationOpportunities: ["هشدار کمبود روی مسیر", "پیشنهاد جابه‌جایی تیم"],
    expectedRoi: "کاهش تأخیر ناشی از نیرو",
    processSteps: steps([
      { label: "نیاز جبهه‌ها", role: "start", owner: "عملیات" },
      { label: "موجودی نیرو", role: "action", owner: "منابع" },
      { label: "بازتخصیص؟", role: "decision", owner: "عملیات" },
      { label: "جابه‌جایی تیم", role: "action", owner: "عملیات" },
      { label: "پایش بهره‌وری", role: "end", owner: "PMO" },
    ]),
    connections: edges(5),
  },
  reporting: {
    id: "wf-board",
    name: "آماده‌سازی گزارش هیئت‌مدیره",
    objective: "تولید روایت معتبر و به‌روز برای حاکمیت",
    whyMatters: "آماده‌سازی تکراری دستی، زمان مدیران را می‌سوزاند و کیفیت را پایین می‌آورد.",
    businessValue: "بریف یکپارچه از ریسک، نقد و پورتفویو",
    kpiImprovements: ["کاهش زمان آماده‌سازی بسته هیئت‌مدیره", "یکپارچگی روایت"],
    actors: ["PMO", "مالی", "مدیرعامل"],
    automationOpportunities: ["پیش‌نویس بریف از داده زنده", "چک راستی‌آزمایی"],
    expectedRoi: "ساعات مدیریتی آزادشده در هر دوره گزارش",
    processSteps: steps([
      { label: "جمع‌آوری سیگنال‌ها", role: "start", owner: "PMO" },
      { label: "راستی‌آزمایی", role: "action", owner: "مالی" },
      { label: "تأیید روایت", role: "decision", owner: "مدیرعامل" },
      { label: "انتشار بسته", role: "end", owner: "PMO" },
    ]),
    connections: edges(4),
  },
  "contract-approval": {
    id: "wf-contract",
    name: "تأیید قرارداد و دستور تغییر",
    objective: "تصمیم شفاف روی تعهدات با دید حاشیه و ریسک",
    whyMatters: "صف تأیید بدون چارچوب اثر، تعهدات زیان‌ده می‌سازد.",
    businessValue: "تصویب مبتنی بر اثر مالی و قراردادی",
    kpiImprovements: ["کاهش زمان صف تأیید", "کاهش دستور تغییر بدون تحلیل حاشیه"],
    actors: ["قراردادها", "مالی", "مدیرعامل"],
    automationOpportunities: ["کارت اثر VO", "مسیر تأیید بر اساس سقف"],
    expectedRoi: "جلوگیری از تعهدات کم‌حاشیه",
    processSteps: steps([
      { label: "ثبت درخواست تغییر", role: "start", owner: "قراردادها" },
      { label: "تحلیل اثر حاشیه/زمان", role: "action", owner: "مالی" },
      { label: "تصویب؟", role: "decision", owner: "مدیرعامل" },
      { label: "ابلاغ و ثبت", role: "end", owner: "قراردادها" },
    ]),
    connections: edges(4),
  },
  "risk-portfolio": {
    id: "wf-risk",
    name: "تشدید ریسک پورتفویو",
    objective: "ارتقای ریسک‌های بحرانی به صف تصمیم اجرایی",
    whyMatters: "ریسک‌های تکراری بدون تشدید، تا بحران دیده نمی‌شوند.",
    businessValue: "صف ریسک اولویت‌دار برای مدیرعامل",
    kpiImprovements: ["کاهش زمان کشف تا اقدام", "پوشش ریسک‌های قرمز"],
    actors: ["PMO", "مدیرعامل", "مدیران پروژه"],
    automationOpportunities: ["تشدید خودکار ریسک قرمز", "خلاصه روزانه ریسک"],
    expectedRoi: "کاهش غافلگیری‌های فصلی",
    processSteps: steps([
      { label: "پایش سلامت پورتفویو", role: "start", owner: "PMO" },
      { label: "رتبه‌بندی ریسک", role: "action", owner: "PMO" },
      { label: "نیاز به تشدید؟", role: "decision", owner: "PMO" },
      { label: "ورود به صف تصمیم", role: "notify", owner: "مدیرعامل" },
      { label: "پیگیری اقدام", role: "end", owner: "پروژه" },
    ]),
    connections: edges(5),
  },
  hse: {
    id: "wf-hse",
    name: "تشدید ایمنی",
    objective: "پیشگیری از توقف کار و حوادث جدی",
    whyMatters: "سیگنال‌های ایمنی تکراری بدون تشدید، به توقف اجباری می‌رسند.",
    businessValue: "واکنش سریع میدانی و مدیریتی",
    kpiImprovements: ["کاهش نزدیک‌به‌حادثه بدون اقدام", "کاهش ریسک توقف"],
    actors: ["HSE", "عملیات", "مدیر پروژه"],
    automationOpportunities: ["هشدار روند حادثه", "چک‌لیست توقف ایمن"],
    expectedRoi: "حفاظت از اعتبار و تداوم کارگاه",
    processSteps: steps([
      { label: "ثبت سیگنال ایمنی", role: "start", owner: "HSE" },
      { label: "ارزیابی شدت", role: "action", owner: "HSE" },
      { label: "توقف لازم است؟", role: "decision", owner: "عملیات" },
      { label: "اقدام اصلاحی", role: "action", owner: "عملیات" },
      { label: "بستن رویداد", role: "end", owner: "HSE" },
    ]),
    connections: edges(5),
  },
  quality: {
    id: "wf-quality",
    name: "کنترل کیفیت اجرایی",
    objective: "کاهش دوباره‌کاری و ادعای کارفرما",
    whyMatters: "NCRهای تکراری بدون چرخه اصلاح، هزینه پنهان می‌سازند.",
    businessValue: "بستن سریع عدم‌انطباق‌های پرهزینه",
    kpiImprovements: ["کاهش هزینه دوباره‌کاری", "کاهش NCR باز"],
    actors: ["کیفیت", "پیمانکار", "مدیر پروژه"],
    automationOpportunities: ["هشدار موج NCR", "پیگیری مهلت اصلاح"],
    expectedRoi: "کاهش هزینه کیفیت و ریسک ادعا",
    processSteps: steps([
      { label: "ثبت عدم‌انطباق", role: "start", owner: "کیفیت" },
      { label: "تحلیل علت", role: "action", owner: "کیفیت" },
      { label: "اصلاح فوری؟", role: "decision", owner: "پروژه" },
      { label: "اجرای اصلاح", role: "action", owner: "پیمانکار" },
      { label: "بستن NCR", role: "end", owner: "کیفیت" },
    ]),
    connections: edges(5),
  },
};

const dashboardCatalog: Record<ConcernDomain, DashboardBlueprint> = {
  delay: {
    id: "db-delay",
    name: "داشبورد اطمینان برنامه",
    whyMonitor: "تأخیر موضوع تکراری جلسات است و نیاز به پایش پیوسته شناوری دارد.",
    questionsAnswered: [
      "کدام مسیر بحرانی در خطر است؟",
      "اثر یک هفته لغزش چقدر است؟",
    ],
    keyKpis: ["شناوری باقی‌مانده", "اطمینان برنامه", "نقاط عطف ۳۰روزه"],
    executiveValue: "تصمیم بازیابی بر اساس واقعیت برنامه نه گزارش خوش‌بینانه",
    strategicImpact: "حفاظت از تعهدات تحویل و اعتبار قراردادی",
    updateFrequency: "روزانه",
    departments: ["PMO", "اجرا", "تدارکات"],
    widgets: [
      { id: "w1", title: "اطمینان برنامه پروژه‌ها", kind: "rings", why: "مقایسه فوری سلامت زمان", span: 2 },
      { id: "w2", title: "توزیع علت تأخیر", kind: "timeline", why: "ریشه تکراری تأخیرها", span: 1 },
      { id: "w3", title: "نقاط عطف در خطر", kind: "list", why: "صف اقدام ۷ روزه", span: 1 },
    ],
  },
  cashflow: {
    id: "db-cash",
    name: "داشبورد جریان نقد اجرایی",
    whyMonitor: "سؤالات نقدینگی تکرار شده و پایش پیوسته لازم است.",
    questionsAnswered: ["نقد تا چند هفته دوام دارد؟", "کجا سرمایه گیر کرده؟"],
    keyKpis: ["موقعیت نقد", "پیش‌بینی ۱۴روزه", "تعهدات پرداخت"],
    executiveValue: "اولویت پرداخت/وصول با یک نگاه",
    strategicImpact: "پایداری عملیات در فشار نقد",
    updateFrequency: "روزانه",
    departments: ["مالی", "مدیریت"],
    widgets: [
      { id: "c1", title: "رودخانه نقدینگی", kind: "river", why: "روند و حوضچه‌های گیرکرده", span: 2 },
      { id: "c2", title: "موقعیت نقد", kind: "metric", why: "عدد تصمیم فوری", span: 1 },
      { id: "c3", title: "تعهدات هفته", kind: "list", why: "صف پرداخت", span: 1 },
    ],
  },
  collection: {
    id: "db-ar",
    name: "داشبورد وصول مطالبات",
    whyMonitor: "وصول موضوع تکراری است و نیاز به دید مطالبات معوق دارد.",
    questionsAnswered: ["کدام صورت‌وضعیت اولویت دارد؟", "متوسط وصول چقدر است؟"],
    keyKpis: ["DSO", "معوق بالای ۱۰ روز", "مبلغ قابل آزادی"],
    executiveValue: "تمرکز تماس‌های وصول روی بیشترین اثر",
    strategicImpact: "آزادی سرمایه در گردش",
    updateFrequency: "روزانه",
    departments: ["مالی", "پروژه"],
    widgets: [
      { id: "a1", title: "مبلغ معوق", kind: "metric", why: "اندازه مسئله", span: 1 },
      { id: "a2", title: "اولویت وصول", kind: "list", why: "صف اقدام", span: 1 },
      { id: "a3", title: "روند وصول", kind: "river", why: "آیا در حال بهبودیم؟", span: 2 },
    ],
  },
  contractor: {
    id: "db-sub",
    name: "داشبورد عملکرد پیمانکاران",
    whyMonitor: "بررسی مکرر پیمانکاران نشان‌دهنده نیاز به پایش مستمر است.",
    questionsAnswered: ["کدام پیمانکار پرریسک است؟", "پرداخت را مشروط کنیم؟"],
    keyKpis: ["امتیاز ظرفیت", "خواب جبهه", "NCR مرتبط"],
    executiveValue: "اهرم پرداخت بر اساس عملکرد",
    strategicImpact: "کاهش وابستگی خطرناک",
    updateFrequency: "هفتگی",
    departments: ["عملیات", "PMO"],
    widgets: [
      { id: "s1", title: "رتبه‌بندی پیمانکاران", kind: "list", why: "اولویت توجه", span: 2 },
      { id: "s2", title: "پیمانکار بحرانی", kind: "metric", why: "هشدار فوری", span: 1 },
      { id: "s3", title: "روند بهره‌وری", kind: "timeline", why: "جهت بهبود/افت", span: 1 },
    ],
  },
  procurement: {
    id: "db-proc",
    name: "داشبورد تدارکات بحرانی",
    whyMonitor: "تدارکات تکراراً مسیر را تهدید کرده است.",
    questionsAnswered: ["کدام قلم مسیر را تهدید می‌کند؟", "کجا کمبود داریم؟"],
    keyKpis: ["اقلام بلندمدت در خطر", "روز تا نیاز", "وضعیت سفارش"],
    executiveValue: "مداخله قبل از توقف جبهه",
    strategicImpact: "پایداری اجرا",
    updateFrequency: "روزانه",
    departments: ["تدارکات", "برنامه"],
    widgets: [
      { id: "p1", title: "اقلام بحرانی", kind: "list", why: "صف تهدید", span: 2 },
      { id: "p2", title: "روز تا نیاز", kind: "metric", why: "فوریت", span: 1 },
      { id: "p3", title: "هم‌ترازی با برنامه", kind: "timeline", why: "فاصله تأمین تا نیاز", span: 1 },
    ],
  },
  equipment: {
    id: "db-equip",
    name: "داشبورد سلامت تجهیزات",
    whyMonitor: "خواب و خرابی تجهیزات موضوع تکراری جلسات بوده است.",
    questionsAnswered: ["کدام تجهیز حیاتی خوابیده؟", "بازتخصیص منطقی است؟"],
    keyKpis: ["بهره‌برداری", "ساعت خواب", "هزینه اجاره"],
    executiveValue: "کاهش هزینه پنهان ناوگان",
    strategicImpact: "آمادگی جبهه‌های کلیدی",
    updateFrequency: "روزانه",
    departments: ["عملیات", "نگهداری"],
    widgets: [
      { id: "e1", title: "بهره‌برداری ناوگان", kind: "rings", why: "سلامت کلی", span: 1 },
      { id: "e2", title: "خواب بحرانی", kind: "list", why: "اقدام فوری", span: 1 },
      { id: "e3", title: "هزینه اجاره", kind: "river", why: "فشار هزینه", span: 2 },
    ],
  },
  budget: {
    id: "db-budget",
    name: "داشبورد کنترل بودجه",
    whyMonitor: "انحراف بودجه به‌صورت تکراری مطرح شده است.",
    questionsAnswered: ["کجا overrun داریم؟", "EAC به کجا می‌رود؟"],
    keyKpis: ["انحراف بودجه", "EAC", "هزینه تأییدنشده"],
    executiveValue: "مهار هزینه قبل از تثبیت زیان",
    strategicImpact: "حفظ سودآوری پروژه",
    updateFrequency: "هفتگی",
    departments: ["مالی", "کنترل پروژه"],
    widgets: [
      { id: "b1", title: "انحراف بودجه", kind: "metric", why: "هشدار عدد", span: 1 },
      { id: "b2", title: "روند EAC", kind: "river", why: "جهت زیان/سود", span: 2 },
      { id: "b3", title: "هزینه‌های باز", kind: "list", why: "صف تصویب", span: 1 },
    ],
  },
  margin: {
    id: "db-margin",
    name: "داشبورد حاشیه اجرایی",
    whyMonitor: "حاشیه سود موضوع تکراری گفتگوهای مدیریتی است.",
    questionsAnswered: ["کدام پروژه حاشیه را می‌خورد؟", "نشتی سود کجاست؟"],
    keyKpis: ["حاشیه پورتفویو", "حاشیه پروژه", "اثر VO"],
    executiveValue: "اولویت اقدام سودمحور",
    strategicImpact: "تحقق سود فصل",
    updateFrequency: "هفتگی",
    departments: ["مالی", "مدیریت", "PMO"],
    widgets: [
      { id: "m1", title: "حاشیه پورتفویو", kind: "metric", why: "وضعیت کلان", span: 1 },
      { id: "m2", title: "نشتی بر اساس علت", kind: "matrix", why: "ریشه افت", span: 1 },
      { id: "m3", title: "پروژه‌های فشارنده حاشیه", kind: "list", why: "تمرکز اقدام", span: 2 },
    ],
  },
  workforce: {
    id: "db-crew",
    name: "داشبورد ظرفیت نیروی اجرایی",
    whyMonitor: "کمبود نیرو به‌طور مکرر مطرح شده است.",
    questionsAnswered: ["کدام جبهه کمبود دارد؟", "بازتخصیص از کجا؟"],
    keyKpis: ["کمبود نفر-روز", "بهره‌وری تیم", "تداخل پروژه‌ها"],
    executiveValue: "تخصیص نیرو بر اساس بحرانی‌بودن",
    strategicImpact: "پایداری اجرا",
    updateFrequency: "روزانه",
    departments: ["عملیات", "منابع"],
    widgets: [
      { id: "r1", title: "کمبود جبهه‌ها", kind: "list", why: "اولویت تأمین", span: 2 },
      { id: "r2", title: "بهره‌وری", kind: "metric", why: "کیفیت تخصیص", span: 1 },
      { id: "r3", title: "تخصیص بین پروژه‌ها", kind: "matrix", why: "تعادل پورتفویو", span: 1 },
    ],
  },
  reporting: {
    id: "db-board",
    name: "داشبورد بریف هیئت‌مدیره",
    whyMonitor: "آماده‌سازی گزارش مدیریتی تکراری است و نیاز به منبع حقیقت واحد دارد.",
    questionsAnswered: ["خلاصه امروز برای هیئت چیست؟", "چه چیزی تغییر کرده؟"],
    keyKpis: ["ریسک‌های قرمز", "نقد", "تصمیم‌های باز"],
    executiveValue: "بریف آماده بدون جمع‌آوری دستی",
    strategicImpact: "حاکمیت مبتنی بر حقیقت",
    updateFrequency: "هفتگی / پیش از جلسه",
    departments: ["PMO", "مالی", "مدیریت"],
    widgets: [
      { id: "h1", title: "سه اولویت هیئت", kind: "list", why: "دستور جلسه", span: 2 },
      { id: "h2", title: "تغییرات هفته", kind: "timeline", why: "از هفته قبل", span: 1 },
      { id: "h3", title: "سلامت پورتفویو", kind: "rings", why: "تصویر کلان", span: 1 },
    ],
  },
  "contract-approval": {
    id: "db-contract",
    name: "داشبورد حاکمیت قرارداد",
    whyMonitor: "تأیید قرارداد و دستور تغییر به‌طور مکرر در صف تصمیم آمده است.",
    questionsAnswered: ["کدام دستور تغییر حاشیه را می‌خورد؟", "صف تأیید چیست؟"],
    keyKpis: ["دستور تغییر باز", "اثر حاشیه", "زمان صف تأیید"],
    executiveValue: "تصویب آگاهانه تعهدات",
    strategicImpact: "کنترل دامنه و سود",
    updateFrequency: "هفتگی",
    departments: ["قراردادها", "مالی"],
    widgets: [
      { id: "v1", title: "صف تأیید", kind: "list", why: "کار امروز", span: 2 },
      { id: "v2", title: "اثر حاشیه دستورهای تغییر", kind: "metric", why: "هزینه تصمیم", span: 1 },
      { id: "v3", title: "عمر صف", kind: "timeline", why: "کندی حاکمیت", span: 1 },
    ],
  },
  "risk-portfolio": {
    id: "db-risk",
    name: "داشبورد ریسک پورتفویو",
    whyMonitor: "سؤالات مکرر درباره بیشترین ریسک نیاز به پایش یکپارچه دارد.",
    questionsAnswered: ["کدام پروژه پورتفویو را تهدید می‌کند؟", "تمرکز ریسک کجاست؟"],
    keyKpis: ["پروژه‌های قرمز", "ماتریس احتمال×اثر", "تغییر روز"],
    executiveValue: "توجه مدیرعامل روی تهدید واقعی",
    strategicImpact: "کاهش غافلگیری فصلی",
    updateFrequency: "روزانه",
    departments: ["PMO", "مدیریت"],
    widgets: [
      { id: "x1", title: "ماتریس ریسک", kind: "matrix", why: "اولویت فضایی", span: 2 },
      { id: "x2", title: "پروژه‌های قرمز", kind: "metric", why: "شمار تهدید", span: 1 },
      { id: "x3", title: "تغییر از دیروز", kind: "list", why: "پویایی ریسک", span: 1 },
    ],
  },
  hse: {
    id: "db-hse",
    name: "داشبورد ایمنی اجرایی",
    whyMonitor: "سیگنال‌های ایمنی تکرار شده و نیاز به دید مدیریتی دارند.",
    questionsAnswered: ["کدام سایت نزدیک توقف است؟", "روند حوادث چیست؟"],
    keyKpis: ["نزدیک‌به‌حادثه", "اقدام باز", "سایت‌های پرریسک"],
    executiveValue: "مداخله قبل از توقف اجباری",
    strategicImpact: "حفاظت از افراد و اعتبار",
    updateFrequency: "روزانه",
    departments: ["HSE", "عملیات"],
    widgets: [
      { id: "hs1", title: "سایت‌های پرریسک", kind: "list", why: "تمرکز بازدید", span: 2 },
      { id: "hs2", title: "روند سیگنال", kind: "timeline", why: "جهت خطر", span: 1 },
      { id: "hs3", title: "اقدامات باز", kind: "metric", why: "انباشت اصلاح", span: 1 },
    ],
  },
  quality: {
    id: "db-quality",
    name: "داشبورد کیفیت اجرایی",
    whyMonitor: "عدم‌انطباق‌ها به‌صورت تکراری مطرح شده‌اند.",
    questionsAnswered: ["کجا دوباره‌کاری هزینه می‌سازد؟", "NCRهای باز کدام‌اند؟"],
    keyKpis: ["NCR باز", "هزینه دوباره‌کاری", "پیمانکار مرتبط"],
    executiveValue: "بستن حلقه کیفیت قبل از ادعا",
    strategicImpact: "کاهش هزینه پنهان کیفیت",
    updateFrequency: "هفتگی",
    departments: ["کیفیت", "پروژه"],
    widgets: [
      { id: "q1", title: "NCRهای باز", kind: "list", why: "صف اصلاح", span: 2 },
      { id: "q2", title: "هزینه دوباره‌کاری", kind: "metric", why: "اثر ریال", span: 1 },
      { id: "q3", title: "روند کیفیت", kind: "river", why: "بهبود یا افت", span: 1 },
    ],
  },
};

export function getWorkflowBlueprint(domain: ConcernDomain): WorkflowBlueprint {
  return JSON.parse(JSON.stringify(workflowCatalog[domain])) as WorkflowBlueprint;
}

export function getDashboardBlueprint(domain: ConcernDomain): DashboardBlueprint {
  return JSON.parse(JSON.stringify(dashboardCatalog[domain])) as DashboardBlueprint;
}
